name: Mirror Repo
on:
  schedule:
    - cron:  '0 3 * * *' # at 3 am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --mirror https://git.earne.link/earnestma/earnestma.git
        cd earnestma.git
        git remote add github "https://eeeee-bot:$TOKEN@github.com/earnestma/earnestma.git"
        git push --mirror github
      env:
        TOKEN: ${{ secrets.TOKEN }}
